config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get 'home/about', to: 'articles#about'
  get "search" => "searches#search"
  resources :users, only: [:index, :show, :edit, :update, :destroy, :create]
  resources :articles, only: [:show, :edit, :update, :new, :destroy, :create, :index] do
    resources :article_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'select_prefecture'
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, presence: true
  validates :article_id, presence: true
  validates_uniqueness_of :article_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_article
  def create
    @favorite = Favorite.create(user_id: current_user.id, article_id: @article.id)
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, article_id: @article.id)
    @favorite.destroy
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if Favorite.find_by(user_id: current_user.id, article_id: article.id) %>
    <%= link_to article_favorites_path(article_id: article.id, id: article.favorites[0].id), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart"><%= article.favorites.count %></span>
    <% end %>
  <% else %>
    <%= link_to article_favorites_path(article.id), method: :post, remote: true do %>
    　<span class="glyphicon glyphicon-heart-empty"><%= article.favorites.count %></span>
    <% end %>
  <% end %>
<% else %>
	<% if article.favorites.count >= 1 %>
  		<span class="glyphicon glyphicon-heart unuser-heart"　data-toggle="tooltip" title="いいね機能はログインユーザーのみ使用できます。"><%= article.favorites.count %></span>
  <% else %>
  		<span class="glyphicon glyphicon-heart-empty unuser-heart"　data-toggle="tooltip" title="いいね機能はログインユーザーのみ使用できます。"><%= article.favorites.count %></span>
  <%end%>
<% end %>

app/views/favorites/create.js.erb
  $('#favorite_<%= @article.id %>').html("<%= j(render partial:'favorites/favorite',  locals: { article: @article }) %>");

app/views/favorites/destroy.js.erb
  $('#favorite_<%= @article.id %>').html("<%= j(render partial: 'favorites/favorite', locals:{ article: @article }) %>");