config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get 'home/about', to: 'articles#about'
  get "search" => "searches#search"
  resources :users, only: [:index, :show, :edit, :update, :destroy, :create]
  resources :articles, only: [:show, :edit, :update, :new, :destroy, :create, :index] do
    resources :article_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'select_prefecture'
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :prefecture
  belongs_to :area
  has_many :article_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :article_images, dependent: :destroy
  accepts_attachments_for :article_images, attachment: :image

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 500 }
  validates :latitude, presence: true
  validates :longitude, presence: true
  validate :presence_image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def presence_image
    errors.add(:article, "写真を投稿してください") if article_images.size == 0
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def index
    # compareFavorite = 0
    # j  = 1
    @articles = Article.all
    @articles_index = Article.all.page(params[:page]).per(6).order(created_at: :desc)
    @all_ranks = Article.find(Favorite.group(:article_id).order('count(article_id) desc').limit(5).pluck(:article_id))
    # 全画像情報取得
    @images = ArticleImage.all.order(created_at: :desc).limit(10)
  end

  def new
    @article = Article.new
    @article.article_images.build
  end

  def create
    @articles = Article.all
    @article = Article.new(article_params)
    @article.score = Language.get_data(article_params[:body])
    @article.user_id = current_user.id
    @user = current_user
    if @article.save
       @article.article_images.each do |article_image|
        tags = Vision.get_image_data(article_image.image)
        tags.each do |tag|
          article_image.tags.create(name: tag['description'], score: tag['score'])
        end
       end
       redirect_to article_path(@article), notice: "記事を投稿しました。"
    else
       render :new
    end
  end

  def edit
    @article = Article.find_by(id: params[:id])
  end

  def update
    @article = Article.find_by(id: params[:id])
    @article.score = Language.get_data(article_params[:body])
    if @article.update(article_params)
        unless article_params[:article_images_images].nil?
         @article.article_images.each do |article_image|
          tags = Vision.get_image_data(article_image.image)
          tags.each do |tag|
            article_image.tags.create(name: tag['description'], score: tag['score'])
          end
         end
       end
      redirect_to article_path(@article), notice: "記事を更新しました。"
    else
      render :edit
    end
  end

  def show
    @article = Article.find_by(id: params[:id])
    @user = @article.user
    @articles = Article.all
    @article_comment = ArticleComment.new
    @images = @article.article_images
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to root_path(article), notice: "記事を削除しました。"
  end

  def select_prefecture
    render partial: 'select_prefecture', locals: { area_id: params[:area_id] }
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :prefecture_id, :area_id, :latitude, :longitude, article_images_images: [])
  end

  def ensure_correct_user
    @article = Article.find(params[:id])
    unless @article.user == current_user
      redirect_to articles_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_footer.html.erb
<div class = "row footer_head">
	<div class = "col-xs-12 ">
		<p class = "foot">© 2020 MountMore </p>
	</div>
</div>

app/views/articles/_graph.html.erb
<% image.each do|f| %>
	<div class = "row">
	<% f.tags.each do |t| %>
		<div class = "col-xs-6 graph-back">
			<div class = "scene-2-content">
				<div class = "charts clearfix">
					<div class = "chart" >
						<div class = "circle-mask-outer left">
							<div class = "circle-mask-inner">
								<div class = "circle-body left"></div>
							</div>
						</div>
						<div class = "circle-mask-outer right">
							<div class = "circle-mask-inner">
								<div class = "circle-body right"></div>
							</div>
						</div>
						<div class = "chart-content">
							<p class = "text">
								<span class = "percent-number"><%= t.score * Constants::PERCENT %></span>
								<span class = "percent-symbol">%</span><br>
								<label class = "tag"><%= t.name %></label>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
		<p class = "no">No.<%= f.id %></p>
	</div>
<% end %>

app/views/articles/_header.html.erb
<div class = "container-fulid" >
  <div class = "row top" >
    <div class = "col-xs-3">
      <%=  image_tag 'logo.jpg', size: '250x150' %>
    </div>
    <!-- ログイン時 -->
          <% if user_signed_in? %>
          <div class = "col-xs-9">
            <div class = "row">
              <div class = "col-xs-12">
                <ul class="nav nav-pills ">
                  <!--ユーザー -->
                  <li class="active">
                    <div class="list_login_name">ようこそ<%= current_user.full_name %>さん！</div>
                  </li>
                  <li class="active">
                    <%= render 'searches/search' %>
                  </li>
                  <li class="active">
                    <button type="button" class="breadcrumb glyphicon glyphicon-picture" data-toggle="modal" data-target="#map_search"></button>
                  </li>
                </ul>
              </div>
            </div>
            <div class = "row">
              <div class = "col-xs-12">
                <ul class = "nav nav-pills">
                  <li class="active">
                    <%= link_to " 記事を投稿する", new_article_path, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-picture" %>
                  </li>
                  <li class="active">
                    <%= link_to " マイページ", user_path(current_user), class: "btn btn-default navbar-btn header__right glyphicon glyphicon-home" %>
                  </li>
                  <li class="active">
                    <%= link_to " 記事一覧", articles_path, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-list-alt" %>
                  </li>
                  <li class="active ">
                    <%= link_to " ユーザー一覧", users_path, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-user" %>
                  </li>
                  <li class="active">
                    <%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-log-out" %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <!--非ログイン -->
          <% else %>
          <div class = "col-xs-9">
            <div class = "row">
              <div class = "col-xs-6">
                <ul class="nav nav-pills ">
                  <!--ユーザー -->
                  <li class="active">
                    <div class = "colspan3"></div>
                  </li>
                  <li class="active">
                    <div class="list_login_name centaer">ようこそ<strong>MountMore</strong>へ！</div>
                  </li>
                  <li class="active">
                    <%= render 'searches/search' %>
                  </li>
                  <li class="active">
                    <button type="button" class="breadcrumb glyphicon glyphicon-picture" data-toggle="modal" data-target="#map_search"></button>
                  </li>
                </ul>
              </div>
            </div>
            <div class = "row">
              <div class = "col-xs-12">
                <ul class = "nav nav-pills">
                  <li class="active">
                    <%= link_to " About", home_about_path, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-leaf" %>
                  </li>
                  <li class="active">
                    <%= link_to " 記事一覧", root_path, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-list-alt" %>
                  </li>
                  <li class="active">
                    <%= link_to " 新規登録", new_user_registration_path, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-pencil"%>
                  </li>
                  <li class="active">
                    <%= link_to " ログイン", new_user_session_path, class: "btn btn-default navbar-btn header__right glyphicon glyphicon-log-in" %>
                  </li>

                </ul>
              </div>
            </div>
          </div>
          <% end %>
  </div>
</div>

app/views/articles/_select_prefecture.html.erb
<%= label :article, :prefecture_id, "都道府県名" %><br>
<%= collection_select :article, :prefecture_id, Prefecture.where(area_id: area_id), :id, :prefecture_name, class:"select-controll" %>

app/views/articles/about.html.erb
<div class = "container-fulid">
	<div class = "row">
		<div class = "about">
			<div class = "col-xs-12">
				<div class = "about_text">
					<h1>ようこそ<strong>MountMore</strong>へ</h1>

					みんなの山での景色や体験を投稿して一緒に共有し、<br>「この山いいな登ってみよう」と思え、<br>
					様々な山に対して挑戦したい気持ちの人が増えてほしいという思いで、<br>
					MountMoreと名付けました。
				</div>
			</div>
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<div class = "container">
  <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "件のエラー") %> により保存できません:</h2>
          <ul>
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
  <% end %>

  <h1>記事を編集する</h1>
  <%= form_for(@article, html: {id: 'post_article'}) do |f| %>
            <%= f.hidden_field :latitude, id: 'form_latitude' %>
            <%= f.hidden_field :longitude, id: 'form_longitude' %>
          <div class = "field">
          <label>タイトル</label>
            <div class="field row">
              <%= f.text_field :title,class: "col-xs-12" %><br>
            </div>
          </div>
          <div class = "field">
            <label>内容</label>
          </div>
          <div class= "field row">
            <%= f.text_area :body, class: "col-xs-12" %>
          </div>
          <div class = "row">
            <%= f.attachment_field :article_images_images, multiple: true, id: "article_image" %>
          </div>
          <h2>地図検索</h2>
          <h5>住所または郵便番号を入力し実行してください</h5>
          <!-- 地名入力用のinputを追加 -->
          <input id="address" type="textbox" value="">

          <!-- buttonをクリックしたらcodeAddressを実行　-->
          <input type="button" value="実行" onclick="codeAddress()">
          <div id='map'></div>
          <div class = "actions row">
            <%= f.submit '内容を更新する', class: "btn btn-primary col-xs-12", id: 'post'%>
          </div>
  <% end %>
              <%= link_to "詳細へ", article_path(@article) %>
              |
             <%= link_to "一覧へ", root_path %>

</div>
<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/

let map
let geocoder
let marker = false
function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: 35.667875, lng: 138.226475},
  zoom: 8
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);
                    // 検索を再度実行時にマーカーが既にあれば先に立てたマーカーは削除
      if (marker != false){marker.setMap(null)}
　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
       marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });

      var latForm = document.getElementById('form_latitude')
      latForm.value = results[0].geometry.location.lat()
      var lngForm = document.getElementById('form_longitude')
      lngForm.value = results[0].geometry.location.lng()
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV["GOOGLE_API_KEY"]%>&callback
=initMap" async defer></script>
<!-- 写真の複数投稿 -->
<script>
  // idについてクリック等のイベントが生じたら、eいかを実行せよという命令。e＝イベント情報を示す。EventListenerとは、イベントを拾う（今回でいうclick
  document.getElementById('post').addEventListener('click',(e)=>{
    e.preventDefault();
    document.getElementById('post_article').name = 'post_article'
    // formに強制的にpost_articleと任意の名前を付与
    // preventDefault()=クリックイベントを無効化。無効化しないと無条件にデータを送信してします。
    var files = document.getElementById("article_image").files;
    // <div><h1>は全てElement。なので、article_imageという名前がついたid(Element)を呼び出す
    // lengthが選んだファイルの数。lengthで数え上げている。filesがhtml上の選択ボックスのtype
    if(files.length>3){
      alert('画像ファイルは3枚以内で投稿して下さい')
    }
    else{
       document.post_article.submit()
       // このnew_articleは5行目で任意につけたフォーム。このdocument.form.submit()で、preventDefault();で無効化したものを再度有効化している。
    }
  });
</script>

app/views/articles/index.html.erb
<div class = "container">
  <div class = "row">
    <!-- 画像スライダーで投稿されている画像全てをスライド表示 -->
    <div class = "col-xs-8">
      <ul class="bxslider">
        <% @images.each do |image| %>
            <li>
                  <%= attachment_image_tag image, :image, format: 'jpeg', size: "500x600" %>
            </li>
        <% end %>
      </ul>
    </div>
    <div class = "col-xs-4 ranking_outside">
      <div class = "text-center"><strong>いいね数ランキング</strong></div>
      <% compareFavorite = 0  %>
      <% j = 1 %>
      <% @all_ranks.each.with_index(1) do |article, i| %>
        <div class = "box__right d-flex justify-content-end">
          <!-- 記事に対するいいねの数でランキングを表示 -->
          <div class="panel panel-default">
            <div class="panel-heading">
              <% if i == 1 %>
                <% compareFavorite = article.favorites.count %>
              <% end %>
              <% if article.favorites.count != compareFavorite %>
                <% j = i %>
                <span class = "badge">
                  第<%= j %>位
                </span>
                <%=link_to article_path(article.id) do%><%= article.title.truncate(10) %><% end %>
                <%= article.favorites.count %>ポイント
                <% compareFavorite = article.favorites.count %>
              <% else %>
                <%  compareFavorite = article.favorites.count%>
                <span class = "badge">
                  第<%= j %>位
                </span>
                <%=link_to article_path(article.id) do%><%= article.title.truncate(10) %><% end %>
                <%= article.favorites.count %>ポイント
              <% end%>
            </div>
              <div class="panel">
              <!-- 記事に関連した複数の写真からidの最初から1つだけ取ってくる -->
                <div class = "row">
                  <div class = "col-xs-4">
                    <% article.article_images.first(1).each do |image| %>
                    <%=attachment_image_tag image, :image, :fill, 100, 100, format: 'jpeg',  class: "img-responsive"%><% end %>
                  </div>
                  <div class = "col-xs-8">
                    <span><%= article.body.truncate(15) %></span>
                  </div>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<!-- 記事一覧を表示 -->
  <div class = "row">
    <% @articles_index.each do |article| %>
      <div class = "col-xs-4 panel-box">
        <div class="panel panel-primary boxed panelzone">
          <div class="panel-header">
            <% article.article_images.first(1).each do |image| %>
            <%=attachment_image_tag image, :image, :fill, 200, 200, format: 'jpeg',  class: "img-responsive"%><% end %>
          </div>
          <div class="panel-body row">
            <h3 class="panel-title col-xs-8"><span class=""><%=link_to article_path(article.id) do%><%= article.title.truncate(10) %><% end %></span></h3>
            <!-- いいね機能 -->
            <div class = "col-xs-4">
              <span id=<%= "favorite_#{article.id}" %> ><%= render 'favorites/favorite', article: article%></span>
            </div>
            <p class="panel-body"><%= article.body.truncate(20) %></p>
          </div>
          <div class="panel-footer">
            <span class="label label-success">投稿者:<%= article.user.user_name %></span><br>
            <small class="text-muted">地方名:<%= article.prefecture.area.area_name %>|都道府県名:<%= article.prefecture.prefecture_name %></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
    <div class = "row">
      <div class = "col-xs-12 text-center">
    <%= paginate  @articles_index%>
      </div>
    </div>
</div>

app/views/articles/new.html.erb
<div class = "container" >
  <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "件のエラー") %> により保存できません:</h2>
          <ul>
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
  <% end %>

	  <div class = "row" >
      <div class = "col-md-12 article-list">
	      <h1>記事投稿</h1>
        <div class ="article-list_article-new">
          <%= form_for(@article, url:articles_path, html: {id: 'post_article'}) do |f| %>
          <%= f.hidden_field :latitude, id: 'form_latitude' %>
          <%= f.hidden_field :longitude, id: 'form_longitude' %>
          <%= f.label :area_id, "地方名" %><br>
          <%= f.collection_select :area_id, Area.all, :id, :area_name, class: "col-xs-12", id: 'article_area_id' %><br>
            <div class = "prefecture">
              <%= render partial: 'select_prefecture', locals: {area_id: Area.first.id}, class: "col-xs-12"%>
            </div>
              <label >タイトル</label>
              <%= f.text_field :title, class: "col-xs-12" %><br>
              <label>内容</label>
              <%= f.text_area :body, class: "col-xs-12 text" %><br>
              <label>写真（３枚以内）</label>
            <div class="alert alert-danger">
              <%= f.attachment_field :article_images_images, multiple: true, id: "article_image" %>
            </div>
              <h2>地図検索</h2>
              <h5>住所または郵便番号を入力し実行してください</h5>
              <!-- 地名入力用のinputを追加 -->
              <input id="address" type="textbox" value="">

              <!-- buttonをクリックしたらcodeAddressを実行　-->
              <input type="button" value="実行" onclick="codeAddress()">
              <div id='map'></div>
              <%= f.submit "記事を投稿する", class: "btn btn-primary btn-lg btn-block", id: 'post'%>
          <%end%>
        </div>
      </div>
    </div>
</div>

<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/

let map
let geocoder
let marker = false
function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: 35.667875, lng: 138.226475},
  zoom: 8
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);
                    // 検索を再度実行時にマーカーが既にあれば先に立てたマーカーは削除
      if (marker != false){marker.setMap(null)}
　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
       marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });

      var latForm = document.getElementById('form_latitude')
      latForm.value = results[0].geometry.location.lat()
      var lngForm = document.getElementById('form_longitude')
      lngForm.value = results[0].geometry.location.lng()
    } else {
      alert('次の理由でジオコードが成功しませんでした: ' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV["GOOGLE_API_KEY"]%>&callback
=initMap" async defer></script>

<!-- 写真複数投稿 -->
<script>
  document.getElementById('post').addEventListener('click',(e)=>{
    e.preventDefault();
    document.getElementById('post_article').name = 'post_article'
    // formに強制的にpost_articleと任意の名前を付与
    // preventDefault()=クリックイベントを無効化。無効化しないと無条件にデータを送信
    var files = document.getElementById("article_image").files;
    // <div><h1>は全てElement。なので、article_imageという名前がついたid(Element)を呼び出す
    // lengthが選んだファイルの数。lengthで数え上げている。filesがhtml上の選択ボックスのtype
    if(files.length>3){
      alert('画像ファイルは3枚以内で投稿して下さい')
    }
    else{
       document.post_article.submit()
    }
  });
</script>

app/views/articles/show.html.erb
<div class = "container article-list">
  <div class = "article-list_article-logo">
		<h1>記事詳細</h1>
  </div>
    <% if user_signed_in? %>
      <span class="label label-success">投稿者:<%=link_to user_path(@user.id) do%><%= @user.user_name %><% end %></span>
      <% else %>
      <span class="label label-success">投稿者:<%= @user.user_name %></span>
    <% end %>
      <!-- いいね機能 -->
      <span id=<%= "favorite_#{@article.id}" %> >
        <%= render 'favorites/favorite', article: @article %>
      </span>
      <!-- コメント数表示 -->
      <span class="label label-info">コメント数:<%= @article.article_comments.count %></span>
    <!-- ログインしているかつ投稿者のみ編集と削除を許可 -->
    <% if user_signed_in? %>
      <% if  @user.id == current_user.id %>
        <span><%= link_to "編集", edit_article_path(@article), class: "label label-success" %></span>
        <span><%= link_to "削除する", article_path(@article), method: :delete, "data-confirm" => "本当に消しますか？", class: "label label-danger" %></span>
      <% end %>
    <% end%>
    <!-- 感情分析値を表示 -->
    <h2>記事から読み取れる感情スコア</h2>
    <h5>（プラス感情に傾いてたら青、マイナス感情に傾いてたら赤のバーで表示されます。）</h5>
    <% if @article.score >= 0 %>
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: <%= @article.score * Constants::PERCENT %>%;">
          <label class = "score-percent"><%= @article.score * Constants::PERCENT %>%</label>
        </div>
      </div>
      <% else %>
      <div class="progress">
        <div class="progress-bar-danger" role="progressbar" style="width: <%= @article.score * -Constants::PERCENT %>%;">
          <label class = "score-percent"><%= @article.score * -Constants::PERCENT %>%</label>
        </div>
      </div>
    <% end %>
      <h2><%= @article.title %></h2>
      <text><%= @article.body %></text>
    <!-- 写真の要素のラベルとその確率を円グラフで表示 -->
    <h2>写真の上位３成分とその確率</h2>
    <ul class="bxslider">
      <%= render 'articles/graph', image: @images %>
    </ul>
    <!-- 画像スライダー -->
    <h2>写真</h2>
    <ul class="bxslider">
      <% @images.each do |image| %>
          <li>
            <strong>No.<%= image.id %></strong>
            <%= attachment_image_tag image, :image, format: 'jpeg', size: "1000x800" %>
          </li>
      <% end %>
    </ul>
    <!-- 地図を表示 -->
    <h2>記事の該当場所</h2>
      <div id='map' data-lat="<%= @article.latitude %>" data-lon="<%= @article.longitude %>"></div>
      <!-- 記事に対するコメントをする。 -->
  <% if user_signed_in? %>
    <% unless  @user.id == current_user.id %>
      <%= form_for [@article, @article_comment] do |f| %>
        <div class = "field">
          <h2>記事へコメント</h2>
        </div>
        <div class= "field row">
          <%= f.text_area :comment, class: "col-xs-12" %>
        </div>
        <div class = "actions row">
          <%= f.submit "コメントする", class: "btn btn-primary col-xs-12" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
    <!-- 記事に対してのコメントを表示 -->
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <td>ユーザー名</td>
            <td>コメント</td>
          </tr>
        </thead>
        <tbody>
          <% @article.article_comments.each do |article_comment| %>
            <tr>
              <td>
                <%= article_comment.user.user_name %>
              </td>
              <td>
                <%= article_comment.comment %>
              </td>
              <!-- コメント主のみ削除可能 -->
              <% if article_comment.user == current_user %>
                <td>
                  <%= link_to "削除する", article_article_comment_path(article_comment.article, article_comment), method: :delete, class: "btn btn-danger pull-right" %>
                </td>
              <% end %>
            </tr>
          <%end%>
        </tbody>
      </table>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV["GOOGLE_API_KEY"]%>&callback=initMap" defer></script>
<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/
const mapElement = document.getElementById('map')
const latitude = parseFloat(mapElement.dataset.lat)
const longitude = parseFloat(mapElement.dataset.lon)
let map
        // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
        // google.maps.Markerインスタンスを生成
        // var marker = new google.maps.Marker({
        //   map: map,
        //   position: results[0].geometry.location
        // });

function initMap(){
  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: latitude, lng: longitude},
    zoom: 8
  });
 // 保存された地図情報からピンをさす

    // google.maps.LatLngインスタンスを生成
    pos = new google.maps.LatLng(
      latitude, //latitude
      longitude //longitude
    );
    default_marker = new google.maps.Marker({
    map: map,
    position: pos,
    icon: {
    url: ' https://maps.google.com/mapfiles/ms/icons/green-dot.png', //アイコンのURL
    scaledSize: new google.maps.Size(40, 40) //サイズ
    }
    });
}
</script>