config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get 'home/about', to: 'articles#about'
  get "search" => "searches#search"
  resources :users, only: [:index, :show, :edit, :update, :destroy, :create]
  resources :articles, only: [:show, :edit, :update, :new, :destroy, :create, :index] do
    resources :article_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'select_prefecture'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :article_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :self_image

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_kana
    validates :first_kana
    validates :post_number
    validates :address
    validates :user_name, uniqueness: true
    validates :email
  end
  validates :introduction, length: { maximum: 60 }
  validates :last_kana, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  validates :first_kana, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  validates :post_number, format: /\A[0-9]+\z/

  def full_name
    last_name + " " + first_name
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ログイン中の現在のユーザーの情報のみ編集できる
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @user = current_user
    @users = User.all.page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path, notice: "アカウントを削除しました。"
  end

  private

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :first_kana, :last_name, :last_kana, :user_name, :post_number, :address, :email, :self_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class = "container">
  <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "件のエラー") %> により保存できません:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <div class = "row">
        <h2>ユーザー情報</h2>
      <div class="col-xs-12">
        <div class="field">
      <%= form_for(@user, url: user_path(@user.id)) do |f| %>
          <label>ユーザー名</label>
          <%= f.text_field :user_name, autofocus: true, class:"form-control", id:"inputName", placeholder:"ユーザー名"%>
        </div> <!--ユーザー名変更-->
        <div class="field">
          <label>郵便番号</label>
          <%= f.text_field :post_number, autofocus: true, class:"form-control", id:"inputEmail" %>
        </div> <!--自己紹介変更-->
          <label>住所</label>
          <%= f.text_field :address, autofocus: true, class:"form-control", id:"inputEmail" %>
 <!--自己紹介変更-->

        <div class="field">
          <label>イメージ画像</label>
          <label class="control-label sr-only" for="inputName">画像</label>
          <%= f.attachment_field :self_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        </div> <!--プロフィール画像変更-->
        <div class="field">
          <label>自己紹介</label>
          <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputEmail" %>
        </div> <!--自己紹介変更-->
        <div class = "actions">
          <%= f.submit "プロフィールを変更する", class: "data-disable-with" %>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "container-fluid">
  <div class = "main-image">
    <div class = "user-list">
        <h2>ユーザー一覧</h2>
        <table class= "table table-hover table-inverse">
	        <thead>
          <tr>
	   		    <th>プロフィール画像</th>
	   		    <th>ユーザー名</th>
			       <th colspan="3"></th>
		      </tr>
	        </thead>
          <tbody>
            <% @users.each do |users|%>
  	           <tr>
                <td><%= attachment_image_tag users, :self_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left self-img", fallback: "no_image.jpg" %></td>
                <td><%= users.user_name %></td>
                <td><%= link_to "詳細へ", user_path(users.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class = "text-center">
      <%= paginate  @users%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container show">
	<div class = "row">
		<div class ="col-xs-8">
  		<h2>記事詳細</h2>
  		<table class= "table table-hover table-inverse"　>
  			<thead>
  				<tr>
  					<th></th>
  					<th>タイトル</th>
  					<th>内容</th>
  					<th colspan="3"></th>
  				</tr>
  			</thead>
    		<tbody>
    			<% @articles.each do |article|%>
    				<tr>
    	      			<td></td>
             			<td><%=link_to article_path(article.id) do%><%= article.title %><% end %></td>
             			<td><%= article.body.truncate(10) %></td>
                  <% if  @user.id == current_user.id %>
                    <td><%= link_to "削除する", article_path(article), method: :delete, "data-confirm" => "本当に消しますか？", class: "label label-danger" %></td>
                  <% end %>
          	</tr>
          <% end %>
    		</tbody>
  		</table>
      <div class = "text-center">
        <%= paginate  @articles%>
      </div>
    </div>
    <!-- 該当ユーザーの情報 -->
    <div class = "col-xs-4">
        <h2>ユーザー情報</h2>
        <%= attachment_image_tag @user, :self_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %>
      <table class = "table">
        <tr>
      		<th>ユーザー名</th>
      		<th><h3 class="profile-name"><%= @user.user_name %></h3></th>
        </tr>
        <tr>
      	 <th>自己紹介</th>
      	 <th><p class = "profile-introduction"><%= @user.introduction %></p></th>
        </tr>
      </table>
    <% if  @user.id == current_user.id %>
      <p><%= link_to "プロフィールを編集する", edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
      <p><%= link_to "アカウントを削除する", user_path(@user.id), method: :delete, "data-confirm" => "削除することによりアカウントに関連した投稿含む全てのデータが削除され、データの復元はできません！本当に削除しますか？", class: "col-xs-12 btn btn-danger" %></p>
    <% end %>
    </div>
  </div>
</div>