config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get 'home/about', to: 'articles#about'
  get "search" => "searches#search"
  resources :users, only: [:index, :show, :edit, :update, :destroy, :create]
  resources :articles, only: [:show, :edit, :update, :new, :destroy, :create, :index] do
    resources :article_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'select_prefecture'
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    type = params[:search_type]
    method = params[:search_method]
    word = params[:search_word]
    if type == "user_match"
      @users = User.search(type, method, word)
      render template: "searches/user_search"
    elsif type == "article_match"
      @articles = Article.search(type, method, word)
      render template: "searches/article_search"
    else
      @areas = Area.search(type, method, word)
      render template: "searches/area_search"
     end
  end
end

app/views/searches/_map_search.html.erb
<div class="modal fade" id="map_search" tabindex="-1">
        <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        <h2 class="modal-title-map">地域検索</h2>
<!-- イメージングマップを表示する -->
          <div id="map-container" ></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
</div>

  <!-- イメージングマップのJS -->
<%= javascript_include_tag 'jquery.japan-map.min.js' %>
<%= javascript_include_tag 'japanmap.js' %>

app/views/searches/_search.html.erb
 <button type="button" class="breadcrumb glyphicon glyphicon-search" data-toggle="modal" data-target="#sampleModal">
 </button>
<%= form_with(url: search_path, local: true, method: :get, id: 'search_form') do %>
<div class="modal fade" id="sampleModal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
				<h4 class="modal-title"><%= text_field(@search_content, :search_word)%>
			</div>
			<div class="modal-body">
    <%= select(@search_content, :search_type, [["user","user_match"], ["article","article_match"]])%></h4>
    <%= select(@search_content, :search_method, [["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]])%>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
<%= submit_tag "検索", class: "btn btn-default" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/searches/area_search.html.erb
<div class = "container main-image">
	<div class = "row">
<h1>地方名検索結果 '<%= params[:search_word] %>' </h1>
		<table class= "table table-hover table-inverse"　>
			<thead>
				<tr>
					<th>投稿者</th>
					<th>タイトル</th>
					<th>都道府県名</th>
					<th colspan="3"></th>
				</tr>
			</thead>
		<tbody>
			<% @areas.each do |area|%>
			<% area.articles.each do |article| %>
				<tr>
	      			<td><%= attachment_image_tag article.user, :self_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %><%= article.user.user_name %></td>
         			<td><%=link_to article_path(article.id) do%><%= article.title %><% end %></td>
         			<td><%= article.prefecture.prefecture_name %></td>
         			</tr>
      		<% end %>
      		<% end %>
		</tbody>
		</table>
	</div>
</div>

app/views/searches/article_search.html.erb
<div class = "container main-image">
	<div class = "row">
<h1>記事検索結果 '<%= params[:search_word] %>' </h1>
		<table class= "table table-hover table-inverse"　>
			<thead>
				<tr>
					<th>タイトル</th>
					<th>本文</th>
				</tr>
			</thead>
		<tbody>
			<% @articles.each do |article|%>
				<tr>
         			<td><%=link_to article_path(article.id) do%><%= article.title %><% end %></td>
         			<td><%= article.body.truncate(15) %></td>
         		</tr>
      		<% end %>
		</tbody>
		</table>
	</div>
</div>

app/views/searches/user_search.html.erb
<div class = "container main-image">
	<div class = "row">
<h1>ユーザー検索結果 '<%= params[:search_word] %>' </h1>
		<table class= "table table-hover table-inverse"　>
			<thead>
				<tr>
					<th>プロフィール画像</th>
					<th>ユーザー名</th>
					<th></th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user|%>
					<tr>
		      			<td><%= attachment_image_tag user, :self_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
		      		<% if user_signed_in? %>
	         			<td><%= link_to user_path(user.id) do %><%= user.user_name %><% end %></td>
	         		<% else %>
	         			<td><%= user.user_name %></td>
	         		<% end %>
	         			<td></td>
	         			</tr>
	      		<% end %>
			</tbody>
		</table>
	</div>
</div>